spring:
  application:
    name: partner_maching-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/partner_maching?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  # session 失效时间
  session:
    timeout: 1440
    store-type: redis   #redis配置，将session默认存在redis
  redis:
    host: localhost
    port: 6379
    password:     #密码
    database: 1   #默认0号库
    # 解决Spring Boot 2.6+与Springfox的兼容性问题
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev

springfox:
  documentation:
    enabled: true


server:
  port: 8080    #端口
  servlet:
    context-path: /api   # api路径
    session:
      cookie:
        domain: localhost

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    # 开启 SQL 日志输出
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

#x-file-storage文件上传
dromara:
  x-file-storage: #文件存储配置
    default-platform: minio-1 #默认使用的存储平台
    thumbnail-suffix: ".min.jpg" #缩略图后缀，例如【.min.jpg】【.png】
    #对应平台的配置写在这里，注意缩进要对齐
    minio:
      - platform: minio-1 # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: NNGwh2CHvyFMMJvfJvad
        secret-key: 2vuce5xwmOvUvwM5K6tvitTEnZIHxyMsI3NIl7op
        end-point: http://100.97.218.1:8009
        bucket-name: leirui-oss
        domain: http://100.97.218.1:8009/leirui-oss/ # 访问域名，注意“/”结尾，例如：http://minio.abc.com/abc/
        base-path: partner_maching/ # 基础路径